### ISSUE TITLE
컴포넌트 기초 스타일 작업

### ISSUE THREAD

**Issue by Juyns** [Samdasugunsugun/TastyZip-Frontend#11]
### Description

컴포넌트의 색상, 배치 위주로 스타일 작업을 진행합니다.
- interaction등은 제외

### To-do

- [x] color scheme 지정
- [x] 컴포넌트 레이아웃 수정
- [x] 컴포넌트에 색상 적용
